### ISSUE TITLE
"?" Property attribute

### ISSUE THREAD

**Issue by Mx-Iris** [leptos-null/ClassDumpRuntime#2]
Please add the property attribute type encoding for the "?", which represents an optional property in the protocol.

Currently, triggering an NSAssert will complain about an unknown property attribute.

<img width="1116" alt="iShot_2024-03-10_22 55 19" src="https://github.com/leptos-null/ClassDumpRuntime/assets/61279231/b8c7aaf4-1b29-4b78-afbd-51c9542e026b">

**Comment by leptos-null** [comment]
Thanks for opening this issue.

```objc
@protocol TestProtocol <NSObject>

@required
@property (nonatomic, readonly, copy) NSNumber *requiredProperty;

@optional
@property (nonatomic, readonly, copy) NSNumber *optionalProperty;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    NSLog(@"requiredProperty: %s", property_getAttributes(protocol_getProperty(@protocol(TestProtocol), "requiredProperty", YES, YES)));
    NSLog(@"optionalProperty: %s", property_getAttributes(protocol_getProperty(@protocol(TestProtocol), "optionalProperty", YES, YES)));
}

@end
```

```txt
requiredProperty: T@"NSNumber",R,C,N
optionalProperty: T@"NSNumber",R,C,N
```

I'm not able to reproduce this in either Obj-C or Obj-C++. What compiler version are you using? Are you using any compiler flags that might be impacting this?

**Comment by Mx-Iris** [comment]
I using Xcode15.3, default Cocoa Application template

**Comment by Mx-Iris** [comment]
It should be caused by Xcode 15.3, I have never encountered this before

**Comment by leptos-null** [comment]
Thanks.

For reference:
- `clang-1500.1.0.2.5` could not reproduce
- `clang-1500.3.9.4` can reproduce

Introduced in https://github.com/llvm/llvm-project/commit/06f10b80847a75b9329174fa7eb0388e214eb19b
